In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/raw/Telco_Customer_Churn.csv")

In [3]:
df_clean = df.copy()

In [4]:
df_clean.nunique()

CustomerID           7043
Count                   1
Country                 1
State                   1
City                 1129
Zip Code             1652
Lat Long             1652
Latitude             1652
Longitude            1651
Gender                  2
Senior Citizen          2
Partner                 2
Dependents              2
Tenure Months          73
Phone Service           2
Multiple Lines          3
Internet Service        3
Online Security         3
Online Backup           3
Device Protection       3
Tech Support            3
Streaming TV            3
Streaming Movies        3
Contract                3
Paperless Billing       2
Payment Method          4
Monthly Charges      1585
Total Charges        6531
Churn Label             2
Churn Value             2
Churn Score            85
CLTV                 3438
Churn Reason           20
dtype: int64

In [5]:
for column in df_clean.columns:
    if df_clean[column].nunique() == 1:
        print(column)

Count
Country
State

In [6]:
columns_to_drop = [
    "CustomerID",
    "Count",
    "Country",
    "State"
]

df_clean = df_clean.drop(columns=columns_to_drop)

In [7]:
df_clean.shape

(7043, 29)

In [8]:
df_clean[["Churn Label", "Churn Value", "Churn Score", "Churn Reason"]].head(10)

,Churn Label,Churn Value,Churn Score,Churn Reason
0,Yes,1,86,Competitor made better offer
1,Yes,1,67,Moved
2,Yes,1,86,Moved
3,Yes,1,84,Moved
4,Yes,1,89,Competitor had better devices
5,Yes,1,78,Competitor offered higher download speeds
6,Yes,1,100,Competitor offered more data
7,Yes,1,92,Competitor made better offer
8,Yes,1,77,Competitor had better devices
9,Yes,1,97,Competitor had better devices

In [9]:
pd.crosstab(df_clean["Churn Label"], df_clean["Churn Value"])

Churn Value     0     1
Churn Label
No           5174     0
Yes             0  1869

In [10]:
df_clean["Churn Score"].describe()

count    7043.000000
mean       58.699418
std        21.525131
min         5.000000
25%        40.000000
50%        61.000000
75%        75.000000
max       100.000000
Name: Churn Score, dtype: float64

In [11]:
df_clean[["Churn Score", "Churn Reason"]].head(10)

   Churn Score                               Churn Reason
0           86               Competitor made better offer
1           67                                      Moved
2           86                                      Moved
3           84                                      Moved
4           89              Competitor had better devices
5           78  Competitor offered higher download speeds
6          100               Competitor offered more data
7           92               Competitor made better offer
8           77              Competitor had better devices
9           97              Competitor had better devices

In [12]:
columns_to_drop = [
    "Churn Label",
    "Churn Score",
    "Churn Reason",
    "CLTV"
]
df_clean = df_clean.drop(columns=columns_to_drop)